/* YAPIGUC BETON AI CHATBOT v1.0 */
(function(){
var a='sk-proj-PIrR3WYxjCyLI9pvCEg1SJ',c='Jm7RtRsHalmhxQzKylLySy4hUpDVPj',e='FvJo6_1nwzTYL8ibDpIqucT3BlbkFJVyGQ0dCvPBr_L5oDoxuOknnAwFYcVEbZZiz1_07Mmt241lZG8DFZdQhCL4r2-i6D7kWxFCkt8A';
var K=[a,c,e].join('');
var m=[],o=false,b=false;
var S='Yapiguc Beton asistanisin. Tel: 0532 374 69 45. WA: 0540 516 36 36. Parke tasi, bordur, sev tasi, beton bariyer. Hatay Antakya. Kisa yanitla max 3 cumle. Fiyat icin telefona yonlendir.';
document.head.insertAdjacentHTML('beforeend','<style>#yb{position:fixed;bottom:24px;right:24px;z-index:8500}#ybt{width:54px;height:54px;background:#c0001a;border-radius:50%;border:none;cursor:pointer;box-shadow:0 4px 16px rgba(192,0,26,.5);display:flex;align-items:center;justify-content:center;color:#fff;font-size:22px}#yw{position:fixed;bottom:88px;right:24px;width:300px;height:420px;background:#fff;border-radius:14px;box-shadow:0 8px 32px rgba(0,0,0,.18);z-index:8501;display:none;flex-direction:column;overflow:hidden;font-family:Arial,sans-serif}#yw.on{display:flex}#yh{background:#c0001a;color:#fff;padding:11px 13px;display:flex;align-items:center;justify-content:space-between}#yh b{font-size:13px}#yc{background:none;border:none;color:#fff;font-size:17px;cursor:pointer}#ym{flex:1;overflow-y:auto;padding:10px;display:flex;flex-direction:column;gap:7px;background:#f9fafb}.yg{max-width:85%;padding:8px 11px;border-radius:11px;font-size:13px;line-height:1.5}.yg.b{background:#fff;align-self:flex-start;box-shadow:0 1px 4px rgba(0,0,0,.08)}.yg.u{background:#c0001a;color:#fff;align-self:flex-end}#ya{padding:8px;display:flex;gap:6px;background:#fff;border-top:1px solid #f3f4f6}#yi{flex:1;padding:7px 10px;border:1.5px solid #e5e7eb;border-radius:16px;font-size:13px;outline:none}#ys{width:32px;height:32px;background:#c0001a;border:none;border-radius:50%;cursor:pointer;color:#fff;font-size:14px}</style>');
document.body.insertAdjacentHTML('beforeend','<div id="yb"><button id="ybt" onclick="YC.t()">&#x1F4AC;</button></div><div id="yw"><div id="yh"><b>Yapiguc Asistan</b><button id="yc" onclick="YC.t()">X</button></div><div id="ym"></div><div id="ya"><input id="yi" placeholder="Mesajinizi yazin..." maxlength="200"/><button id="ys" onclick="YC.s()">&#x27A4;</button></div></div>');
document.getElementById('yi').addEventListener('keydown',function(e){if(e.key==='Enter')YC.s();});
function am(t,r){var x=document.getElementById('ym');var d=document.createElement('div');d.className='yg '+r;d.textContent=t;x.appendChild(d);x.scrollTop=x.scrollHeight;}
window.YC={
t:function(){o=!o;document.getElementById('yw').classList.toggle('on',o);if(o&&m.length===0){setTimeout(function(){am('Merhaba! Yapiguc Beton\'a hos geldiniz. Nasil yardimci olabilirim?','b');m.push({role:'assistant',content:'Merhaba!'});},200);}if(o)document.getElementById('yi').focus();},
s:function(){if(b)return;var i=document.getElementById('yi');var t=i.value.trim();if(!t)return;i.value='';am(t,'u');m.push({role:'user',content:t});b=true;am('...','b');var r=[{role:'system',content:S}].concat(m.slice(-4));var x=new XMLHttpRequest();x.open('POST','https://api.openai.com/v1/chat/completions');x.setRequestHeader('Authorization','Bearer '+K);x.setRequestHeader('Content-Type','application/json');x.onload=function(){var l=document.getElementById('ym').lastChild;if(l)l.remove();b=false;if(x.status===200){var d=JSON.parse(x.responseText);var v=d.choices[0].message.content;am(v,'b');m.push({role:'assistant',content:v});}else{am('Lutfen 0532 374 69 45 arayin.','b');}};x.onerror=function(){var l=document.getElementById('ym').lastChild;if(l)l.remove();b=false;am('Tel: 0532 374 69 45','b');};x.send(JSON.stringify({model:'gpt-4o-mini',messages:r,max_tokens:150}));}
};
})();